import {
  BankOutlined,
  CommentOutlined,
  DashboardOutlined,
  DollarOutlined,
  FileTextOutlined,
  FrownOutlined,
  FundProjectionScreenOutlined,
  FundViewOutlined,
  InsertRowLeftOutlined,
  LaptopOutlined,
  ProfileOutlined,
  ReadOutlined,
  SettingOutlined,
  TeamOutlined,
  ThunderboltOutlined,
  ToolOutlined,
  TransactionOutlined,
  TruckOutlined,
  UnorderedListOutlined,
  UserAddOutlined,
  UserOutlined,
} from '@ant-design/icons';

const icons: any = {
  DashboardOutlined: <DashboardOutlined />,
  UserOutlined: <UserOutlined />,
  UnorderedListOutlined: <UnorderedListOutlined />,
  UserAddOutlined: <UserAddOutlined />,
  SettingOutlined: <SettingOutlined />,
  LaptopOutlined: <LaptopOutlined />,
  ProfileOutlined: <ProfileOutlined />,
  InsertRowLeftOutlined: <InsertRowLeftOutlined />,
  BankOutlined: <BankOutlined />,
  ToolOutlined: <ToolOutlined />,
  TruckOutlined: <TruckOutlined />,
  DollarOutlined: <DollarOutlined />,
  FileTextOutlined: <FileTextOutlined />,
  FrownOutlined: <FrownOutlined />,
  TransactionOutlined: <TransactionOutlined />,
  FundProjectionScreenOutlined: <FundProjectionScreenOutlined />,
  FundViewOutlined: <FundViewOutlined />,
  ReadOutlined: <ReadOutlined />,
  CommentOutlined: <CommentOutlined />,
  ThunderboltOutlined: <ThunderboltOutlined />,
  TeamOutlined: <TeamOutlined />,
};

export default icons;
